version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: fsw-foods-postgres
    environment:
      POSTGRES_USER = postgres
      POSTGRES_PASSWORD = password
    ports:
      - "5432:5432"
    volunes:
      - ./.postgres-data:/var/lib/postgres/data
volumes:
  .postgres-data